- src: https://github.com/websoft9dev/role_common
  version: master

- src: https://github.com/websoft9dev/role_cloud
  version: master

- src: https://github.com/websoft9dev/role_docker
  version: master

- src: https://github.com/websoft9dev/role_nodejs
  version: master

- src: https://github.com/websoft9dev/role_init_password
  version: master

- src: https://github.com/websoft9dev/role_preend
  version: master

- src: https://github.com/websoft9dev/role_end
  version: master