name: Relese Plugin-Appstore To Azure

on: workflow_dispatch

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    env:
      CI: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.2.0

      - name: Install dependencies
        run: npm install

      - name: Build
        run: yarn build

      - name: Copy Data、Logos、Screenshots To Plugin
        run: cp -R data/  build/static/

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: build plugin
