name: Fetch data from contentful graphql

on: workflow_dispatch

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch data from contentful graphql
        env:
          ACCESS_TOKEN: ${{ secrets.CONTENTFUL_GRAPHQLTOKEN }}
          LOCALES: "en-US,zh-CN"
        run: |
          mkdir -p appmanage/static/json
          IFS=',' read -ra LOCALE_ARRAY <<< "$LOCALES"
          for LOCALE in "${LOCALE_ARRAY[@]}"; do
            curl -X POST \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer $ACCESS_TOKEN" \
              -d '{"query":"query($locale: String){catalog(id: \"2Yp0TY3kBHgG6VDjsHZNpK\",locale:$locale) {linkedFrom(allowedLocales:[\"en-US\"]) {catalogCollection(limit:20) {items {key position title linkedFrom(allowedLocales:[\"en-US\"]) {catalogCollection(limit:20) {items {key title position}}}}}}}}","variables":{"locale":"'$LOCALE'"}}' \
              https://graphql.contentful.com/content/v1/spaces/ffrhttfighww > appmanage/static/json/catalog_$LOCALE.json
          done

      - name: Fetch Product data from contentful graphql
        env:
          ACCESS_TOKEN: ${{ secrets.CONTENTFUL_GRAPHQLTOKEN }}
          LOCALES: "en-US,zh-CN"
          LIMIT: 100
        run: |
          mkdir -p appmanage/static/json
          IFS=',' read -ra LOCALE_ARRAY <<< "$LOCALES"
          for LOCALE in "${LOCALE_ARRAY[@]}"; do
            SKIP=0
            TOTAL=0
            while [ $SKIP -le $TOTAL ]; do
              RESPONSE=$(curl -X POST \
                -H "Content-Type: application/json" \
                -H "Authorization: Bearer $ACCESS_TOKEN" \
                -d '{"query":"query($locale: String,$skip: Int){productCollection(locale:$locale,where:{appStore:true},limit: '$LIMIT', skip: $skip) {total items {sys {id} key hot trademark summary overview websiteurl description screenshots distribution vcpu memory storage logo {imageurl} catalogCollection(limit:15) {items {key title catalogCollection(limit:5){items{key title}}}}}}}", "variables":{"locale":"'$LOCALE'", "skip":'$SKIP'}}' \
                https://graphql.contentful.com/content/v1/spaces/ffrhttfighww)
              echo $RESPONSE | jq '.data.productCollection.items' >> appmanage/static/json/product_$LOCALE.json
              TOTAL=$(echo $RESPONSE | jq '.data.productCollection.total')
              SKIP=$((SKIP + LIMIT))
            done
          done

      - name: Install ossutil
        run: |
          wget http://gosspublic.alicdn.com/ossutil/1.7.6/ossutil64
          chmod 755 ossutil64
      - name: Configure ossutil
        run: ./ossutil64 config -e ${{ secrets.OSS_ENDPOINT }} -i ${{ secrets.OSS_ACCESS_KEY_ID }} -k ${{ secrets.OSS_ACCESS_KEY_SECRET }}

      # - name: Download file from OSS
      #   run: ./ossutil64 cp oss://libs-websoft9-com/Websoft9/logo/product/ plugins/appstore/build/static/data/images/ -r --update
      - name: Download logo
        env:
          LOCALES: "en-US,zh-CN"
          DEST_DIR: "plugins/appstore/build/static/data/images/logo/"
          FILENAME: $(basename $1)
        run: |
          mkdir -p $DEST_DIR
          IFS=',' read -ra LOCALE_ARRAY <<< "$LOCALES"
          for LOCALE in "${LOCALE_ARRAY[@]}"; do
            jq -r '.[].logo.imageurl | sub("https://libs.websoft9.com";"oss://libs-websoft9-com")' appmanage/static/json/product_$LOCALE.json | xargs -n 1 ./ossutil64 cp --update $DEST_DIR/${{ env.FILENAME }}
          done

      - name: Download screenshots
        env:
          LOCALES: "en-US,zh-CN"
          DEST_DIR: "plugins/appstore/build/static/data/images/screenshots/"
          FILENAME: $(basename $1)
        run: |
          mkdir -p $DEST_DIR
          IFS=',' read -ra LOCALE_ARRAY <<< "$LOCALES"
          for LOCALE in "${LOCALE_ARRAY[@]}"; do
            jq -r '.[].screenshots[] | sub("https://libs.websoft9.com";"oss://libs-websoft9-com")' appmanage/static/json/product_$LOCALE.json | xargs -n 1 ./ossutil64 cp --update $DEST_DIR/${{ env.FILENAME }}
          done

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update catalog.json
