name: Test Pull Request

on: workflow_dispatch

jobs:
  Test_Pull_Request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2    
     
      - name: Checkout websoft9
        uses: actions/checkout@v2
        with:
          repository: Websoft9/websoft9
          ref: main    
      
      - name: Update Version in websoft9/version.json
        run: |
          version=$(jq -r '.Version' appstore.json)
          echo "PLUGIN_VERSION=$version" >> $GITHUB_OUTPUT
          jq -r --arg version "${{ env.PLUGIN_VERSION }}" '.PLUGINS.APPSTORE = $version' version.json > version.json.tmp
          mv version.json.tmp version.json

      - name: Commit changes
        run: |
          git config user.name "zhaojing1987"
          git config user.email "jing.zhao@websoft9.com"
          git add version.json
          git commit -m "Update the APPSTORE value in version.json to: ${{ env.PLUGIN_VERSION }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.MYGITHUB_ADMIN_TOKEN }}
          branch: auto-branch-${{ github.run_number }}
          delete-branch: true
          commit-message: Update report
          title: "Update the appstore version: ${{ env.PLUGIN_VERSION }}"
          body: "This is my modification, please review and merge it"
          labels: "Update Appstore Version"
