name: Test Pull Request

on: workflow_dispatch

jobs:
  Test_Pull_Request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout websoft9
        uses: actions/checkout@v2
        with:
          repository: Websoft9/websoft9
          ref: main    
      
      - name: Update Version in websoft9/version.json
        run: |
          version=0.0.2
          echo "PLUGIN_VERSION=$version" >> $GITHUB_OUTPUT
          jq -r --arg version "$version" '.PLUGINS.APPSTORE = $version' version.json > version.json.tmp
          mv version.json.tmp version.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.ZJ_ADMIN_TOKEN }}
          branch: update-appstore-version-${{ github.run_number }}
          delete-branch: true
          commit-message: Update Appstore Version
          title: "App Store Releases New Version"
          body: "Update the APPSTORE value in version.json to: ${{ steps.update_data.outputs.PLUGIN_VERSION }}"
