name: Upload Artifact To Azure Blob

on: workflow_dispatch

jobs:
  Upload_Artifact_To_Azure_Blob:
    runs-on: ubuntu-latest
    env:
      CI: false

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/download_data/action

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.2.0

      - name: Install dependencies
        run: npm install

      - name: Build
        run: yarn build

      - name: Copy data、logos、screenshots to build
        run: cp -R data/  build/static/

      - name: Read plugin version
        id: read-version
        run: |
          version=$(jq -r '.Version' appstore.json)
          echo "PLUGIN_VERSION=$version" >> $GITHUB_ENV

      - name: Create Zip Archive
        run: |
          mv build appstore
          zip -r appstore-${{ env.PLUGIN_VERSION }}.zip appstore/

      - name: Upload To Azure Blob
        uses: LanceMcCarthy/Action-AzureBlobUpload@v2
        with:
          connection_string: ${{ secrets.AZURE_STORAGE_ARTIFACT }}
          container_name: release
          source_folder: appstore-${{ env.PLUGIN_VERSION }}.zip
          destination_folder: ./websoft9/plugin
          delete_if_exists: true
          fail_if_source_empty: true

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Build Plugin and Upload Artifact to Azure Blob
